// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProductProperty struct {
	Name     string `json:"Name"`
	Code     string `json:"Code"`
	Required bool   `json:"Required"`
}
